server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    maxIdle: 0
    minIdle: 10
    minEvictableIdleTimeMillis: 10
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

security:
  oauth2:
    client:
      clientId: 3MVG9ahGHqp.k2_wb8eUMtoR38.rDfPf3U.RJFm1y1CkMrbKRwhfdjnP8HT5N4iz5tNIYd.uMrOzIhdmgm4fA
      clientSecret: 6648238551529648018
      clientAuthenticationScheme: form
      authenticationScheme: query
      tokenName: oauth_token
      accessTokenUri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/token
      userAuthorizationUri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/authorize
      grantType: authorizationCode

    resource:
      userInfoUri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/userinfo

