server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver


  jpa:
    properties:
      hibernate:
        dialect: hibernate.dialect">org.hibernate.dialect.Oracle10gDialect