server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    maxIdle: 0
    minIdle: 10
    minEvictableIdleTimeMillis: 10
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

security:
  oauth2:
    client:
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
      accessTokenUri: ${ACCESS_TOKEN_URI}
      userAuthorizationUri: ${USER_AUTH_URI}
      tokenName: authorization_code
      authenticationScheme: form
      clientAuthenticationScheme: header
      grantType: authorization_code
      useCurrentUri: false
    resource:
      userInfoUri: ${USER_INFO_URI}

